#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.2
#  in conjunction with Tcl version 8.6
#    May 09, 2020 06:09:24 PM -04  platform: Windows NT

import sys

try:
    from tkinter import*
except ImportError:
    from tkinter import*

try:
    import ttk
    py3 = False
except ImportError:
    from tkinter import ttk
    py3 = True

def set_Tk_var():
    global combobox
    combobox = StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    import SortingGUI
    SortingGUI.vp_start_gui()




